INSERT INTO authority (name)
SELECT * FROM (SELECT 'LOGISTA') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM authority WHERE name = 'LOGISTA'
) LIMIT 1;

INSERT INTO authority (name)
SELECT * FROM (SELECT 'CLIENTE') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM authority WHERE name = 'CLIENTE'
) LIMIT 1;

INSERT INTO authority (name)
SELECT * FROM (SELECT 'VENDEDOR') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM authority WHERE name = 'VENDEDOR'
) LIMIT 1;